# NexusOne AI Platform - Production Configuration

[api]
enabled = true
port = 54321
schemas = ["public", "auth", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://app.nexusone.ai"
additional_redirect_urls = [
  "https://nexusone.ai/auth/callback",
  "https://app.nexusone.ai/auth/callback",
  "https://www.nexusone.ai/auth/callback"
]
jwt_expiry = 86400 # 24 hours
refresh_token_rotation_enabled = true
security_captcha_enabled = true
security_update_password_require_reauthentication = true

# OAuth Providers
[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "https://hbfgtdxvlbkvkrjqxnac.supabase.co/auth/v1/callback"

[auth.external.facebook]
enabled = true
client_id = "env(FACEBOOK_APP_ID)"
secret = "env(FACEBOOK_APP_SECRET)"
redirect_uri = "https://hbfgtdxvlbkvkrjqxnac.supabase.co/auth/v1/callback"

[auth.external.github]
enabled = true
client_id = "env(GITHUB_CLIENT_ID)"
secret = "env(GITHUB_CLIENT_SECRET)"
redirect_uri = "https://hbfgtdxvlbkvkrjqxnac.supabase.co/auth/v1/callback"

[db]
port = 54322
major_version = 15
max_connections = 100
log_level = "info"

[realtime]
enabled = true
ip_version = "dual"
max_concurrent_users = 1000

[storage]
enabled = true
file_size_limit = "100MB"
buckets = [
  { name = "avatars", public = true },
  { name = "landing-pages", public = true },
  { name = "generated-content", public = true },
  { name = "user-uploads", public = false },
  { name = "video-assets", public = true },
  { name = "ai-generated", public = false },
  { name = "documents", public = false },
  { name = "audio-files", public = true },
  { name = "templates", public = true },
  { name = "campaigns", public = false }
]

[functions]
enabled = true
timeout = 300000 # 5 minutes
memory = 2048 # 2GB

# Edge Functions Configuration
[[functions.imports]]
map = { "supabase": "https://esm.sh/@supabase/supabase-js@2" }

[[functions.imports]]
map = { "cors": "https://deno.land/x/cors@v1.2.2/mod.ts" }

[analytics]
enabled = true
backend = "postgres"

[inbound_email]
enabled = false

[studio]
enabled = true
port = 54323