#!/bin/bash

# Manual Deployment Commands for NexusOne AI
# Run these commands in your terminal one by one

echo "🚀 NexusOne AI Manual Deployment Commands"
echo "========================================="

echo ""
echo "📦 1. Install Dependencies"
echo "npm install -g vercel"
echo "npm install -g supabase"
echo "npm install"

echo ""
echo "🔧 2. Build Application"
echo "npm run build"

echo ""
echo "🌐 3. Deploy to Vercel"
echo "vercel login"
echo "vercel --prod"

echo ""
echo "⚙️ 4. Set Environment Variables in Vercel Dashboard"
echo "Go to: https://vercel.com/dashboard"
echo "Select your project → Settings → Environment Variables"
echo ""
echo "Add these variables:"
echo "VITE_SUPABASE_URL=your_supabase_url"
echo "VITE_SUPABASE_ANON_KEY=your_supabase_anon_key"
echo "OPENAI_API_KEY=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"
echo "OPENAI_ASSISTANT_ID=asst_0jsx8eD6P3W9XGsSRRNU2Pfd"
echo "ELEVENLABS_API_KEY=sk_189b755ede03dfdf1633da77e125d682b44c1ddb54b08a07"
echo "REPLICATE_API_TOKEN=r8_HbwQQ4NxMfhVPy0BS0xqOMkERd9B5JM440l66"
echo "LUMA_API_KEY=luma-12423eab-79ee-4f52-ad44-00c485686cf2-ab1b6b03-15a1-4c76-b056-6765bf41ab05"
echo "GUPSHUP_API_KEY=sk_d5fe7cdab5164e53bcbffdc428fd431e"
echo "CJ_DROPSHIPPING_API_KEY=5e0e680914c6462ebcf39059b21e70a9"
echo "FACEBOOK_ACCESS_TOKEN=EAAI0DOV8GvcBPK4ZBUTybkGl66FwZA1s45Dx3cSjOVEO4lzZAifzVR6lIoVbW6HcsP2L7x4b0065VirgfhzyfIGNCCA9QCynR3twQB01ZCqjolM7b0QfGtBpj5ZCZA5kyWONQsaYmZBRvy1ByAziVPZAot50fp9ZB4ro71pZAPk7iK4ynEMkhG2LBqUmg2VFWZCPAYQ74T3ocUZCL7u69pCaZAhqUe29gMZALb2jZB5YWQrfHbreY0hIgZDZD"
echo "UNSPLASH_ACCESS_KEY=-zZ5LsB2CAMUhbPca_UKw31ngzc1W3_hfxSPdz_aBUE"

echo ""
echo "🗄️ 5. Deploy Supabase Edge Functions"
echo "supabase login"
echo "supabase link --project-ref YOUR_PROJECT_REF"
echo ""
echo "Deploy functions one by one:"
echo "supabase functions deploy ai-campaign-generator"
echo "supabase functions deploy ai-content-generator"
echo "supabase functions deploy ai-video-generator"
echo "supabase functions deploy cj-dropshipping-catalog"
echo "supabase functions deploy cj-dropshipping-order"
echo "supabase functions deploy dropshipping-import"
echo "supabase functions deploy facebook-ads-manager"
echo "supabase functions deploy generate-income"
echo "supabase functions deploy magic-pages-generator"
echo "supabase functions deploy nexbrain-assistant"
echo "supabase functions deploy product-scraper"
echo "supabase functions deploy whatsapp-automation"
echo "supabase functions deploy user-analytics"
echo "supabase functions deploy payment-processor"
echo "supabase functions deploy image-generator"
echo "supabase functions deploy video-creator"
echo "supabase functions deploy landing-page-builder"
echo "supabase functions deploy campaign-optimizer"
echo "supabase functions deploy lead-manager"
echo "supabase functions deploy notification-service"

echo ""
echo "✅ 6. Verify Deployment"
echo "curl -f https://your-vercel-url.vercel.app"

echo ""
echo "🎉 Deployment Complete!"
echo "Your NexusOne AI platform should now be live!"
echo ""
echo "Next steps:"
echo "1. Test all features with production API keys"
echo "2. Configure custom domain"
echo "3. Set up monitoring and analytics"
echo "4. Launch marketing campaigns"
echo ""
echo "Happy selling! 💰"