[build]
  publish = "dist"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "https://lqcbkqacqgikpucuuhsm.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxY2JrcWFjcWdpa3B1Y3V1aHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4MDQ2MjcsImV4cCI6MjA1MDM4MDYyN30.qrcqjovFtqPYOqTlNJIGSqGULJO8POzFGMhHmJxgfTM"
  
# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions (for future Netlify Functions if needed)
[functions]
  directory = "netlify/functions"